baseURL = "https://alexandre-normand.github.io/resume/"
languageCode = "en-us"
title = "Alexandre Normand's Online Resume"
theme = "hugo-sp-minimal"
publishDir = "docs"

[params]
  themeStyle = "simple"
  renderType = "single"
